### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by pierreguillot** [pierreguillot/HoaLibrary-Analyzer#1]
- [ ] hoa.2d.vector.analyzer~-help.pd
- [ ] hoa.3d.vector.analyzer~-help.pd
- [ ] hoa.2d.vector.plot
- [ ] hoa.3d.vector.plot
- [ ] hoa.2d.vector.recorder~
- [ ] hoa.2d.vector.recorder~
- [ ] hoa.3d.vector.energy~ (error ? see plot)
